ALTER TABLE `fruta_icarga` ADD `FECHAETDREAL_ICARGA` DATE NULL AFTER `FECHAETAREAL_ICARGA`;
ALTER TABLE `fruta_icarga` ADD `FECHASTACKINGF_ICARGA` DATE NULL AFTER `FECHASTACKING_ICARGA`;
ALTER TABLE `fruta_dicarga` ADD `CANTIDAD_PALLET_DICARGA` INT NULL AFTER `CANTIDAD_ENVASE_DICARGA`;
ALTER TABLE `fruta_icarga` ADD `NUMEROCOURIER_ICARGA` INT NULL AFTER `NCONTENEDOR_ICARGA`;